server {
    listen 80;
    listen [::]:80;
    server_name localhost _;

    location / {
        root /usr/share/nginx/html;
        try_files /index.html =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
